sudo: true

language: java

jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"

before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.2.deb && sudo service elasticsearch start
    - sleep 10

install:
  - echo "<settings><servers><server><id>bintray</id><username>\${env.BINTRAY_USER}</username><password>\${env.BINTRAY_KEY}</password></server></servers></settings>" > ~/.m2/settings.xml
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] || [[ $TRAVIS_TAG = v* ]]; then GOAL=deploy; else GOAL=install; fi
  - if [[ $TRAVIS_TAG = v* ]]; then ADDITIONAL_PROFILES=release; mvn -q -U org.seedstack:seedstack-maven-plugin:release; else ADDITIONAL_PROFILES=snapshots; fi

script: mvn -q -U -T 2 -Pbuild-number,compatibility,bintray,javadoc,v68,$ADDITIONAL_PROFILES $GOAL jacoco:report

after_success: mvn -q coveralls:report -DrepoToken=$COVERALLS_TOKEN
